apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
type: application
name: strimoid
icon: https://strm.pl/android-chrome-192x192.png
version: 0.1.0
dependencies:
  - name: postgresql
    version: 11.9.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.3.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
