version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.22.1
  - dependency-name: jeremykendall/php-domain-parser
    versions:
    - 6.0.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: "@bugsnag/js"
    versions:
    - 7.6.0
    - 7.7.0
    - 7.8.0
    - 7.9.0
    - 7.9.2
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
    - 4.6.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.9
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: postcss-loader
    versions:
    - 5.0.0
    - 5.1.0
    - 5.2.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
  - dependency-name: react-player
    versions:
    - 2.8.2
    - 2.9.0
  - dependency-name: handlebars
    versions:
    - 4.7.7
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.1
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.13
  - dependency-name: expose-loader
    versions:
    - 2.0.0
  - dependency-name: imports-loader
    versions:
    - 2.0.0
  - dependency-name: bootstrap
    versions:
    - 4.6.0
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.2
  - dependency-name: webpack-assets-manifest
    versions:
    - 5.0.1
