<?php

use Strimoid\Models\Entry;

class EntryTableSeeder extends BaseSeeder {

    public function run()
    {
        DB::table('entries')->delete();

        // Get list of user and group ids
        $groupIds = DB::table('groups')->lists('id');
        $userIds = DB::table('users')->lists('id');

        // Insert 50 elements filled with random data
        $faker = \Faker\Factory::create();

        foreach (range(1, 50) as $x)
        {
            // Use static id generated by using first 6 chars of $x hash
            $id = substr(md5($x), 0, 6);

            $randomUser = (string) $userIds[array_rand($userIds)];
            $randomGroup = (string) $groupIds[array_rand($groupIds)];

            Entry::create([
                'id' => $id,
                'created_at' => $faker->dateTimeThisDecade,
                'group_id' => $randomGroup,
                'text' => $faker->text(512),
                'user_id' => $randomUser,
            ]);
        }
    }

}
