version: "3.9"
services:
  nginx:
    image: nginx:1.19-alpine
    ports:
      - "8000:80"
    links:
      - php
    volumes:
      - ./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: .
    image: quay.io/strimoid/strimoid
    depends_on:
     - postgres
     - redis
  postgres:
    image: postgres:13-alpine
    environment:
     - POSTGRES_USER=strimoid
     - POSTGRES_PASSWORD=strimoid
  redis:
    image: redis:6.0-alpine
