version: '2'
services:
  web:
    build: .
    image: quay.io/strimoid/strimoid
    ports:
     - "8000:80"
    links:
     - beanstalkd
     - postgres
     - redis
  beanstalkd:
    image: schickling/beanstalkd
  postgres:
    image: postgres:12-alpine
    environment:
     - POSTGRES_USER=strimoid
     - POSTGRES_PASSWORD=strimoid
  redis:
    image: redis:6.0-alpine
