version: '2'
services:
  nginx:
    image: nginx:1.18-alpine
    ports:
      - "8000:80"
    links:
      - php
    volumes:
      - ./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: .
    image: quay.io/strimoid/strimoid
    links:
     - beanstalkd
     - postgres
     - redis
  beanstalkd:
    image: schickling/beanstalkd
  postgres:
    image: postgres:12-alpine
    environment:
     - POSTGRES_USER=strimoid
     - POSTGRES_PASSWORD=strimoid
  redis:
    image: redis:6.0-alpine
