services:
  php:
    build: .
    image: quay.io/strimoid/strimoid
    ports:
      - "8000:80"
    depends_on:
     - postgres
     - redis
  postgres:
    image: postgres:16.2-alpine
    environment:
     - POSTGRES_USER=strimoid
     - POSTGRES_PASSWORD=strimoid
  redis:
    image: redis:7.2-alpine
