version: '2'
services:
  web:
    image: strimoid/strimoid
    ports:
     - "8000:8000"
    volumes:
     - .:/code
    depends_on:
     - mariadb
     - redis
  mariadb:
    image: mariadb
  redis:
    image: redis
