version: "3.9"
services:
  php:
    environment:
     - DB_HOST=postgres
     - REDIS_HOST=redis
    volumes:
     - .:/src
     - ./config/docker/php/dev.ini:/usr/local/etc/php/conf.d/custom.ini
     - ./config/docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
  php-init:
    build: .
    image: quay.io/strimoid/strimoid
    environment:
      - DB_HOST=postgres
    command: "/src/artisan migrate:fresh --seed"
    restart: on-failure
  postgres:
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"
  pgweb:
    image: sosedoff/pgweb
    environment:
      - DATABASE_URL=postgres://strimoid:strimoid@postgres:5432/strimoid?sslmode=disable
    ports:
      - "5433:8081"
    links:
      - postgres
