version: '2'
services:
  web:
    environment:
     - APP_ENV=local
     - APP_DEBUG=true
     - DB_HOST=postgres
     - DB_PORT=5432
     - DB_USERNAME=strimoid
     - DB_PASSWORD=strimoid
     - REDIS_HOST=redis
     - REDIS_PORT=6379
    volumes:
     - .:/src
  postgres:
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"
  pgweb:
    image: sosedoff/pgweb
    environment:
      - DATABASE_URL=postgres://strimoid:strimoid@postgres:5432/strimoid?sslmode=disable
    ports:
      - "5433:8081"
    links:
      - postgres
