version: '2'
services:
  web:
    environment:
     - APP_ENV=local
     - APP_DEBUG=true
     - DB_HOST=postgres
     - DB_PORT=5432
     - DB_USERNAME=strimoid
     - DB_PASSWORD=strimoid
     - REDIS_HOST=redis
     - REDIS_PORT=6379
    volumes:
     - .:/src
  postgres:
    ports:
      - "5432:5432"
