apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "strimoid.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "strimoid.name" . }}
    helm.sh/chart: {{ include "strimoid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "strimoid.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "strimoid.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.beanstalkd.enabled }}
            - name: QUEUE_DRIVER
              value: beanstalkd
            - name: BEANSTALKD_HOST
              value: {{ template "strimoid.beanstalkd.fullname" . }}
            {{- end }}
            {{- if .Values.postgresql.enabled }}
            - name: DB_HOST
              value: {{ template "strimoid.postgresql.fullname" . }}
            - name: DB_DATABASE
              value: {{ .Values.postgresql.postgresDatabase | quote }}
            - name: DB_PORT
              value: {{ .Values.postgresql.service.port | quote }}
            {{- end }}
            {{- if .Values.redis.enabled }}
            - name: CACHE_DRIVER
              value: redis
            - name: REDIS_HOST
              value: {{ template "strimoid.redis.fullname" . }}
            - name: REDIS_PORT
              value: {{ .Values.redis.master.port | quote }}
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote  }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ template "strimoid.fullname" . }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: storage
              mountPath: /src/storage/uploads
              subPath: uploads
          {{- end }}
          ports:
            - name: fastcgi
              containerPort: 9000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.persistence.enabled }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "strimoid.fullname" .) }}
    {{- end -}}
