apiVersion: v1
kind: Secret
metadata:
  name: {{ template "strimoid.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "strimoid.name" . }}
    helm.sh/chart: {{ include "strimoid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  DB_USERNAME: {{ .Values.postgresql.postgresUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
