default: &default
  working_directory: ~/strimoid
  docker:
    - image: quay.io/osm-browser/ci

version: 2
jobs:
  build:
    <<: *default
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          command: docker-compose up -d
          environment:
            COMPOSE_FILE: docker-compose.yml
      - run: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io
      - run: docker push quay.io/strimoid/strimoid
      - run: helm dependency build ./chart
      - persist_to_workspace:
          root: chart
          paths:
            - '*'
  deploy:
    <<: *default
    steps:
      - attach_workspace:
          at: chart
      - run:
          command: |
            echo $K8S_CA | base64 -d > ca.crt
            kubectl config set-cluster default --server=$K8S_URL --certificate-authority=ca.crt
            kubectl config set-credentials default --token=$(echo $K8S_TOKEN | base64 -d)
            kubectl config set-context default --cluster=default --user=default
            kubectl config use-context default
      - run:
          command: |
            helm upgrade strimoid ./chart \
              --values <(helm get values strimoid) \
             --install --timeout 600 --wait

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: default
      - deploy:
          context: default
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master
