name: Build

on:
  push:
    branches-ignore:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker-compose up -d --build
        env:
          IMAGE_TAG: ${{ github.sha }}
          COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
