name: Build & deploy - production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Setup Docker configuration
        run: mkdir -p $HOME/.docker; echo $DOCKER_CONFIG | base64 -d > $HOME/.docker/config.json
        env:
          DOCKER_CONFIG: ${{ secrets.DOCKER_CONFIG }}
      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: quay.io/strimoid/strimoid:${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ secrets.ARGO_REPO }}
          token: ${{ secrets.GIT_TOKEN }}
      - name: Setup Kubernetes credentials
        run: mkdir -p $HOME/.kube; echo $K8S_CONFIG | base64 -d > $HOME/.kube/config; chmod 0600 $HOME/.kube/config
        env:
          K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
      - name: Update manifest
        run: |
          cd strimoid/prod
          kustomize edit set image strimoid=quay.io/strimoid/strimoid:$GITHUB_SHA
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add strimoid/prod/kustomization.yaml
          git commit -m "Bump strm-prod to $GITHUB_SHA (GitHub Actions)"
