name: Build & deploy - QA

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Setup Docker configuration
        run: mkdir -p $HOME/.docker; echo $DOCKER_CONFIG | base64 -d > $HOME/.docker/config.json
        env:
          DOCKER_CONFIG: ${{ secrets.DOCKER_CONFIG }}
      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: quay.io/strimoid/strimoid:${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Kubernetes credentials
        run: mkdir -p $HOME/.kube; echo $K8S_CONFIG | base64 -d > $HOME/.kube/config; chmod 0600 $HOME/.kube/config
        env:
          K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
      - name: Build Helm chart dependencies
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add strimoid https://strimoid.github.io/helm-charts/
          helm dependency build ./chart
      - name: Upgrade Helm release
        run: |
          helm upgrade strm-qa ./chart \
            --wait --set image.tag=${{ github.sha }} \
            --values <(helm get values strm-qa)
